# Generated by Django 3.2.13 on 2022-06-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTest1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='django',
            old_name='age',
            new_name='Age',
        ),
        migrations.RemoveField(
            model_name='django',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='django',
            name='name',
        ),
        migrations.AddField(
            model_name='django',
            name='Email',
            field=models.EmailField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='django',
            name='First_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='django',
            name='Last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='django',
            name='Mobile',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='django',
            name='Password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='django',
            name='Username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
