# Generated by Django 3.2.13 on 2022-06-24 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTest1', '0002_auto_20220622_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='django',
            old_name='First_name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='django',
            name='Last_name',
        ),
    ]
